# conf SonarQub, contiene chiave e nome leggibile per la dashboard
sonar.projectKey=node-express-boilerplate
sonar.projectName=node-express-boilerplate

# cartelle di test e source code
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# output report di sicurezza in formato lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# file esclusi
sonar.exclusions=node_modules/**,coverage/**,bin/**,src/docs/**
sonar.coverage.exclusions=tests/**,src/config/**,src/app.js

